<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function home_page_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'home_page_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function home_page_user_login_form_submit($form, FormStateInterface $form_state) {
  $url = Url::fromRoute('view.praticiens.page_1');
  $form_state->setRedirectUrl($url);
}
